name: 2) Container Image Release [Continuous Delivery]
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    
permissions:
  contents: write
  pull-requests: read 
  issues: read
  packages: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Container image
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Container image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build \
          --file Dockerfile \
          --tag gatekeeper_image:latest \
          --tag gatekeeper_image:$(date +%s) \
          .

    - name: Upload Container image as a release asset
      uses: actions/upload-artifact@v2
      with:
        name: gatekeeper_image
        path: gatekeeper_image

  release:
    needs: build
    name: Release Container image
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_id }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} v${tag#v}"
