name: 3) Container Image Deployment [Continuous Deployment]

on:
  # Run every time a change is pushed to 'release'.
  push:
    branches: [release]
  workflow_dispatch: # Allow manual execution of this workflow
    
# Define environment variables for the workflow.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gatekeeper

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      
    steps:
      # Perform checkout of the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up docker buildx to build the image
      - name: Set up Buildx action
        uses: docker/setup-buildx-action@v1
            
      # Build & push the image to the GHCR
      - name: Build and push container image to GHCR
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build \
            --file Dockerfile \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --label "org.opencontainers.image.source=${{ env.IMAGE_NAME }}" \
            --label "org.opencontainers.image.description=GateKeeper" \
            --label "org.opencontainers.image.licenses=MIT" \
            .
          docker image push ghcr.io/run2go/${{ env.IMAGE_NAME }}:latest
