name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build \
          --file Dockerfile \
          --tag my-image-name:latest \
          --tag my-image-name:$(date +%s) \
          .

