name: Docker Image CI/CD

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Upload Docker image
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build \
          --file Dockerfile \
          --tag gatekeeper_image:latest \
          --tag gatekeeper_image:$(date +%s) \
          .

    - name: Upload Docker image as a release asset
      uses: actions/upload-artifact@v2
      with:
        name: gatekeeper_image
        path: gatekeeper_image

  release:
    needs: build
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_id }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} v${tag#v}" \
        #--generate-notes \
